export const authTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
};

export const commonTypes = {
  SET_INITIAL_DATA: "SET_INITIAL_DATA",
  SET_CURRENT_EXAM: "SET_CURRENT_EXAM",
  SET_EXAM_QUESTIONS: "SET_EXAM_QUESTIONS",
  SET_EXAM_ANSWERS: "SET_EXAM_ANSWERS",
};
